addrTcp: 207.154.236.143:8080
addrQuic: 207.154.236.143:8081
addrNats: 207.154.236.143:4222
addrGrpc: 207.154.236.143:8082
connString: sqlite.db
certFile: ./config/certs/client/cert.pem
keyFile: ./config/certs/client/key.pem
rootCa: ./config/certs/rootCA.pem
