addrTcp: 46.101.186.135:8080
addrQuic: 46.101.186.135:8081
addrNats: 46.101.186.135:4222
connString: sqlite.db
certFile: ./config/certs/client/cert.pem
keyFile: ./config/certs/client/key.pem
rootCa: ./config/certs/rootCA.pem
