linters:
  fast: false
  enable-all: true
  disable:
    # Deprecated:
    - interfacer
    - golint
    - maligned
    - scopelint
      # Annoying:
    - nlreturn
    - gochecknoglobals
    - prealloc
    - gomnd
    - wsl
    - varnamelen
run:
  skip-dirs:
    - api
