version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: always
    networks:
      spaceship-engine-production:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  spaceship-engine-production:

volumes:
  postgres-data:
