version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: always
    networks:
      db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  data-loader-server:
    image: data-loader-server
    build:
      context: ..
      dockerfile: ./build/data-loader-server.dockerfile
    restart: always
    volumes:
      - ../config/certs:/certs/:z
      - ../config/data-loader-server/:/config/:z
    networks:
      db:
      mq:
    ports:
      - "8080:8080"

  nats-server:
    image: nats:2.6
    restart: always
    command:
      - --tls
      - --tlscert=/certs/nats-server/cert.pem
      - --tlskey=/certs/nats-server/key.pem
      - --tlscacert=/certs/rootCA.pem
      - --tlsverify
    volumes:
      - ../config/certs/:/certs/:z
    networks:
      mq:
    ports:
      - "4222:4222"
      - "8222:8222"

networks:
  db:
  mq:

volumes:
  postgres-data:
