client: nats

input:
  connString:
    postgresql: "host=localhost port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"

output:
  server:
    address: localhost:8080
  nats:
    address: localhost:4222
  excel:
    file: "/results/report.xlsx"
