// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportPrinterClient is the client API for ReportPrinter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportPrinterClient interface {
	Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error)
}

type reportPrinterClient struct {
	cc grpc.ClientConnInterface
}

func NewReportPrinterClient(cc grpc.ClientConnInterface) ReportPrinterClient {
	return &reportPrinterClient{cc}
}

func (c *reportPrinterClient) Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error) {
	out := new(PrintResponse)
	err := c.cc.Invoke(ctx, "/ReportPrinter/Print", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportPrinterServer is the server API for ReportPrinter service.
// All implementations must embed UnimplementedReportPrinterServer
// for forward compatibility
type ReportPrinterServer interface {
	Print(context.Context, *PrintRequest) (*PrintResponse, error)
	mustEmbedUnimplementedReportPrinterServer()
}

// UnimplementedReportPrinterServer must be embedded to have forward compatible implementations.
type UnimplementedReportPrinterServer struct {
}

func (UnimplementedReportPrinterServer) Print(context.Context, *PrintRequest) (*PrintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Print not implemented")
}
func (UnimplementedReportPrinterServer) mustEmbedUnimplementedReportPrinterServer() {}

// UnsafeReportPrinterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportPrinterServer will
// result in compilation errors.
type UnsafeReportPrinterServer interface {
	mustEmbedUnimplementedReportPrinterServer()
}

func RegisterReportPrinterServer(s grpc.ServiceRegistrar, srv ReportPrinterServer) {
	s.RegisterService(&ReportPrinter_ServiceDesc, srv)
}

func _ReportPrinter_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportPrinterServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReportPrinter/Print",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportPrinterServer).Print(ctx, req.(*PrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportPrinter_ServiceDesc is the grpc.ServiceDesc for ReportPrinter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportPrinter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReportPrinter",
	HandlerType: (*ReportPrinterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Print",
			Handler:    _ReportPrinter_Print_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/report-printer.proto",
}
